// Demo data for Utopia Exhibition Demo
// Using high-quality Unsplash images for realistic presentation

export const DEMO_DEALS = [
    {
        _id: 'demo-1',
        title: 'Flat 40% Off Premium Coffee',
        description: 'Start your morning right with our signature blend. Valid on all beverages above ₹200.',
        category: 'Cafe',
        originalPrice: 450,
        discountedPrice: 270,
        discountPercentage: 40,
        images: ['https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800'],
        merchantId: { _id: 'm1', name: 'Cafe Coffee Day', logo: '' },
        termsAndConditions: ['Valid until 31st Jan', 'Minimum order ₹200'],
        isActive: true,
    },
    {
        _id: 'demo-2',
        title: 'Buy 1 Get 1 Free Pizza',
        description: 'Double the taste, double the fun! Get a free pizza on every order.',
        category: 'Restaurant',
        originalPrice: 599,
        discountedPrice: 299,
        discountPercentage: 50,
        images: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800'],
        merchantId: { _id: 'm2', name: 'Dominos Pizza', logo: '' },
        termsAndConditions: ['Valid on dine-in only', 'Not combinable with other offers'],
        isActive: true,
    },
    {
        _id: 'demo-3',
        title: '25% Off Biriyani Festival',
        description: 'Authentic Hyderabadi biriyani at unbeatable prices. Family pack available!',
        category: 'Restaurant',
        originalPrice: 350,
        discountedPrice: 262,
        discountPercentage: 25,
        images: ['https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800'],
        merchantId: { _id: 'm3', name: 'Paradise Biriyani', logo: '' },
        termsAndConditions: ['Valid on all variants', 'Takeaway available'],
        isActive: true,
    },
    {
        _id: 'demo-4',
        title: 'Ice Cream Sundae Special',
        description: 'Cool down with our premium Belgian chocolate sundae. Perfect for summer!',
        category: 'Desserts',
        originalPrice: 250,
        discountedPrice: 149,
        discountPercentage: 40,
        images: ['https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800'],
        merchantId: { _id: 'm4', name: 'Pabbas Ice Cream', logo: '' },
        termsAndConditions: ['Valid all day', 'Add toppings free'],
        isActive: true,
    },
    {
        _id: 'demo-5',
        title: '30% Off Fashion Week',
        description: 'Trendy ethnic wear collection. New arrivals just dropped!',
        category: 'Fashion',
        originalPrice: 2999,
        discountedPrice: 2099,
        discountPercentage: 30,
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
        merchantId: { _id: 'm5', name: 'FabIndia', logo: '' },
        termsAndConditions: ['Minimum purchase ₹1500', 'Exchange within 7 days'],
        isActive: true,
    },
    {
        _id: 'demo-6',
        title: 'Spa & Wellness Package',
        description: 'Full body massage + facial at premium prices. Relax and rejuvenate.',
        category: 'Wellness',
        originalPrice: 3500,
        discountedPrice: 1999,
        discountPercentage: 43,
        images: ['https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800'],
        merchantId: { _id: 'm6', name: 'Kaya Spa', logo: '' },
        termsAndConditions: ['Appointment required', 'Valid Mon-Fri'],
        isActive: true,
    },
    {
        _id: 'demo-7',
        title: '₹500 Off on Electronics',
        description: 'Latest gadgets and accessories. Flat discount on orders above ₹5000.',
        category: 'Electronics',
        originalPrice: 5999,
        discountedPrice: 5499,
        discountPercentage: 8,
        images: ['https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800'],
        merchantId: { _id: 'm7', name: 'Croma', logo: '' },
        termsAndConditions: ['Valid on select items', 'Installation free'],
        isActive: true,
    },
    {
        _id: 'demo-8',
        title: 'Burger Combo Meal',
        description: 'Classic burger + fries + drink. The ultimate combo at unbeatable price!',
        category: 'Fast Food',
        originalPrice: 399,
        discountedPrice: 249,
        discountPercentage: 38,
        images: ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800'],
        merchantId: { _id: 'm8', name: 'Burger King', logo: '' },
        termsAndConditions: ['Dine-in and takeaway', 'Upsize available'],
        isActive: true,
    },
    {
        _id: 'demo-9',
        title: 'Books @ 50% Off',
        description: 'Bestsellers and new releases. Perfect for book lovers!',
        category: 'Books',
        originalPrice: 599,
        discountedPrice: 299,
        discountPercentage: 50,
        images: ['https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800'],
        merchantId: { _id: 'm9', name: 'Crossword', logo: '' },
        termsAndConditions: ['Buy 2 get extra 10% off', 'All genres included'],
        isActive: true,
    },
    {
        _id: 'demo-10',
        title: 'Premium Gym Membership',
        description: 'Monthly membership with personal trainer sessions. Get fit now!',
        category: 'Fitness',
        originalPrice: 4999,
        discountedPrice: 2999,
        discountPercentage: 40,
        images: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800'],
        merchantId: { _id: 'm10', name: 'Gold\'s Gym', logo: '' },
        termsAndConditions: ['Valid for new members', 'Includes locker access'],
        isActive: true,
    },
    {
        _id: 'demo-11',
        title: 'Chinese Feast for 2',
        description: 'Soup + 2 starters + 2 mains + dessert. Perfect date night meal!',
        category: 'Restaurant',
        originalPrice: 1800,
        discountedPrice: 1199,
        discountPercentage: 33,
        images: ['https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800'],
        merchantId: { _id: 'm11', name: 'Mainland China', logo: '' },
        termsAndConditions: ['Valid on weekdays', 'Reservation required'],
        isActive: true,
    },
    {
        _id: 'demo-12',
        title: 'Fresh Groceries 20% Off',
        description: 'Organic fruits and vegetables delivered fresh to your doorstep.',
        category: 'Grocery',
        originalPrice: 1000,
        discountedPrice: 800,
        discountPercentage: 20,
        images: ['https://images.unsplash.com/photo-1542838132-92c53300491e?w=800'],
        merchantId: { _id: 'm12', name: 'More Supermarket', logo: '' },
        termsAndConditions: ['Minimum order ₹500', 'Free delivery above ₹1000'],
        isActive: true,
    },
];

export const DEMO_FRIENDS = [
    { _id: 'f1', profile: { name: 'Arjun Sharma', avatar: '' }, email: 'arjun@example.com', xp: 15600, rank: 'Gold II' },
    { _id: 'f2', profile: { name: 'Priya Patel', avatar: '' }, email: 'priya@example.com', xp: 23400, rank: 'Gold III' },
    { _id: 'f3', profile: { name: 'Rahul Verma', avatar: '' }, email: 'rahul@example.com', xp: 8900, rank: 'Silver I' },
    { _id: 'f4', profile: { name: 'Ananya Reddy', avatar: '' }, email: 'ananya@example.com', xp: 45000, rank: 'Platinum I' },
    { _id: 'f5', profile: { name: 'Vikram Singh', avatar: '' }, email: 'vikram@example.com', xp: 12300, rank: 'Silver III' },
    { _id: 'f6', profile: { name: 'Sneha Kapoor', avatar: '' }, email: 'sneha@example.com', xp: 6700, rank: 'Silver I' },
    { _id: 'f7', profile: { name: 'Aditya Kumar', avatar: '' }, email: 'aditya@example.com', xp: 31000, rank: 'Gold III' },
    { _id: 'f8', profile: { name: 'Kavya Nair', avatar: '' }, email: 'kavya@example.com', xp: 19800, rank: 'Gold II' },
];

export const DEMO_FEED = [
    { _id: 'act1', type: 'deal_claimed', user: { profile: { name: 'Arjun Sharma' } }, data: { merchantName: 'Cafe Coffee Day' }, createdAt: new Date().toISOString() },
    { _id: 'act2', type: 'level_up', user: { profile: { name: 'Priya Patel' } }, data: { level: 25 }, createdAt: new Date(Date.now() - 3600000).toISOString() },
    { _id: 'act3', type: 'mission_completed', user: { profile: { name: 'Rahul Verma' } }, data: { missionTitle: 'Weekend Explorer' }, createdAt: new Date(Date.now() - 7200000).toISOString() },
    { _id: 'act4', type: 'deal_claimed', user: { profile: { name: 'Ananya Reddy' } }, data: { merchantName: 'Mainland China' }, createdAt: new Date(Date.now() - 10800000).toISOString() },
    { _id: 'act5', type: 'level_up', user: { profile: { name: 'Vikram Singh' } }, data: { level: 18 }, createdAt: new Date(Date.now() - 14400000).toISOString() },
    { _id: 'act6', type: 'deal_claimed', user: { profile: { name: 'Sneha Kapoor' } }, data: { merchantName: 'Pabbas Ice Cream' }, createdAt: new Date(Date.now() - 18000000).toISOString() },
    { _id: 'act7', type: 'mission_completed', user: { profile: { name: 'Aditya Kumar' } }, data: { missionTitle: 'Social Butterfly' }, createdAt: new Date(Date.now() - 21600000).toISOString() },
    { _id: 'act8', type: 'deal_claimed', user: { profile: { name: 'Kavya Nair' } }, data: { merchantName: 'FabIndia' }, createdAt: new Date(Date.now() - 25200000).toISOString() },
];

export const DEMO_LEADERBOARD = [
    { _id: 'lb1', name: 'Meera Krishnan', xp: 156000, rank: 'Platinum III', position: 1, avatar: '🏆' },
    { _id: 'lb2', name: 'Rohan Mehta', xp: 134500, rank: 'Platinum II', position: 2, avatar: '🥈' },
    { _id: 'lb3', name: 'Ishita Gupta', xp: 112300, rank: 'Platinum I', position: 3, avatar: '🥉' },
    { _id: 'lb4', name: 'Arjun Sharma', xp: 98700, rank: 'Gold III', position: 4, avatar: '⭐' },
    { _id: 'lb5', name: 'Priya Patel', xp: 87600, rank: 'Gold III', position: 5, avatar: '⭐' },
    { _id: 'lb6', name: 'Siddharth Rao', xp: 76500, rank: 'Gold II', position: 6, avatar: '🌟' },
    { _id: 'lb7', name: 'Ananya Reddy', xp: 65400, rank: 'Gold II', position: 7, avatar: '🌟' },
    { _id: 'lb8', name: 'Vikram Singh', xp: 54300, rank: 'Gold I', position: 8, avatar: '✨' },
    { _id: 'lb9', name: 'Kavya Nair', xp: 43200, rank: 'Silver III', position: 9, avatar: '💫' },
    { _id: 'lb10', name: 'Rahul Verma', xp: 32100, rank: 'Silver II', position: 10, avatar: '💫' },
];

export const DEMO_FRIEND_REQUESTS = [
    { _id: 'req1', requester: { _id: 'r1', profile: { name: 'Tanvi Saxena' }, email: 'tanvi@example.com' }, status: 'pending' },
    { _id: 'req2', requester: { _id: 'r2', profile: { name: 'Harsh Joshi' }, email: 'harsh@example.com' }, status: 'pending' },
];

export const DEMO_SQUADS = [
    { _id: 'sq1', name: 'Deal Hunters', members: 8, totalSavings: 45600, weeklyXP: 12400 },
    { _id: 'sq2', name: 'Manipal Foodies', members: 12, totalSavings: 78900, weeklyXP: 23500 },
    { _id: 'sq3', name: 'College Savers', members: 6, totalSavings: 23400, weeklyXP: 8700 },
];
