import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Share,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import {
  ArrowLeft,
  Download,
  Share2,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Calendar,
  FileText,
  CreditCard,
  Wallet,
} from 'lucide-react-native';
import { theme } from '@/constants/theme';

interface RevenueReport {
  period: string;
  totalRevenue: number;
  totalRedemptions: number;
  avgOrderValue: number;
  topCampaign: string;
  growth: number;
}

const monthlyReports: RevenueReport[] = [
  {
    period: 'November 2025',
    totalRevenue: 12450,
    totalRedemptions: 342,
    avgOrderValue: 36.4,
    topCampaign: '50% Off All Pizzas',
    growth: 23,
  },
  {
    period: 'October 2025',
    totalRevenue: 10120,
    totalRedemptions: 298,
    avgOrderValue: 33.9,
    topCampaign: 'Buy 2 Get 1 Free',
    growth: 15,
  },
  {
    period: 'September 2025',
    totalRevenue: 8790,
    totalRedemptions: 245,
    avgOrderValue: 35.9,
    topCampaign: '30% Off Spa Services',
    growth: -5,
  },
];

const paymentBreakdown = [
  { method: 'UPI', amount: 7890, percentage: 63.4, icon: Wallet },
  { method: 'Card', amount: 3240, percentage: 26.0, icon: CreditCard },
  { method: 'Cash', amount: 1320, percentage: 10.6, icon: DollarSign },
];

export default function RevenueReportsScreen() {
  const router = useRouter();
  const [selectedPeriod, setSelectedPeriod] = useState<'month' | 'quarter' | 'year'>('month');

  const handleShareReport = async () => {
    try {
      await Share.share({
        message: `Revenue Report - November 2025\n\nTotal Revenue: ₹12,450\nRedemptions: 342\nAverage Order: ₹36.4\n\nGenerated by UMA Business`,
      });
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
          <ArrowLeft size={24} color={theme.colors.text} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Revenue Reports</Text>
        <TouchableOpacity onPress={handleShareReport} style={styles.shareButton}>
          <Share2 size={20} color={theme.colors.primary} />
        </TouchableOpacity>
      </View>

      <ScrollView showsVerticalScrollIndicator={false}>
        {/* Period Selector */}
        <View style={styles.periodContainer}>
          {(['month', 'quarter', 'year'] as const).map((period) => (
            <TouchableOpacity
              key={period}
              style={[
                styles.periodButton,
                selectedPeriod === period && styles.periodButtonActive,
              ]}
              onPress={() => setSelectedPeriod(period)}>
              <Text
                style={[
                  styles.periodText,
                  selectedPeriod === period && styles.periodTextActive,
                ]}>
                {period.charAt(0).toUpperCase() + period.slice(1)}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Summary Card */}
        <View style={styles.summaryCard}>
          <View style={styles.summaryHeader}>
            <View style={styles.summaryIcon}>
              <DollarSign size={24} color={theme.colors.primary} />
            </View>
            <View style={styles.summaryContent}>
              <Text style={styles.summaryLabel}>Total Revenue</Text>
              <Text style={styles.summaryValue}>₹12,450</Text>
              <View style={styles.growthBadge}>
                <TrendingUp size={14} color={theme.colors.success} />
                <Text style={styles.growthText}>+23% from last month</Text>
              </View>
            </View>
          </View>
          
          <View style={styles.summaryDivider} />
          
          <View style={styles.summaryStats}>
            <View style={styles.summaryStat}>
              <Text style={styles.summaryStatLabel}>Redemptions</Text>
              <Text style={styles.summaryStatValue}>342</Text>
            </View>
            <View style={styles.summaryStatDivider} />
            <View style={styles.summaryStat}>
              <Text style={styles.summaryStatLabel}>Avg Order</Text>
              <Text style={styles.summaryStatValue}>₹36.4</Text>
            </View>
          </View>
        </View>

        {/* Payment Methods */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Payment Breakdown</Text>
          <View style={styles.paymentCards}>
            {paymentBreakdown.map((payment, index) => (
              <View key={index} style={styles.paymentCard}>
                <View style={styles.paymentHeader}>
                  <View style={styles.paymentIconContainer}>
                    <payment.icon size={18} color={theme.colors.primary} />
                  </View>
                  <Text style={styles.paymentMethod}>{payment.method}</Text>
                </View>
                <Text style={styles.paymentAmount}>₹{payment.amount.toLocaleString()}</Text>
                <View style={styles.progressBar}>
                  <View 
                    style={[
                      styles.progressFill, 
                      { width: `${payment.percentage}%` }
                    ]} 
                  />
                </View>
                <Text style={styles.paymentPercentage}>{payment.percentage}% of total</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Monthly Reports */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionTitle}>Monthly Reports</Text>
            <TouchableOpacity style={styles.downloadButton}>
              <Download size={16} color={theme.colors.primary} />
              <Text style={styles.downloadText}>Export</Text>
            </TouchableOpacity>
          </View>
          
          <View style={styles.reportsList}>
            {monthlyReports.map((report, index) => (
              <TouchableOpacity key={index} style={styles.reportCard}>
                <View style={styles.reportIcon}>
                  <FileText size={20} color={theme.colors.primary} />
                </View>
                <View style={styles.reportContent}>
                  <View style={styles.reportHeader}>
                    <Text style={styles.reportPeriod}>{report.period}</Text>
                    <View style={[
                      styles.reportGrowth,
                      { backgroundColor: report.growth > 0 ? 'rgba(0, 217, 163, 0.1)' : 'rgba(255, 107, 107, 0.1)' }
                    ]}>
                      {report.growth > 0 ? (
                        <TrendingUp size={12} color={theme.colors.success} />
                      ) : (
                        <TrendingDown size={12} color="#FF6B6B" />
                      )}
                      <Text style={[
                        styles.reportGrowthText,
                        { color: report.growth > 0 ? theme.colors.success : '#FF6B6B' }
                      ]}>
                        {Math.abs(report.growth)}%
                      </Text>
                    </View>
                  </View>
                  <View style={styles.reportStats}>
                    <Text style={styles.reportStat}>
                      Revenue: ₹{report.totalRevenue.toLocaleString()}
                    </Text>
                    <Text style={styles.reportStatSeparator}>•</Text>
                    <Text style={styles.reportStat}>
                      {report.totalRedemptions} orders
                    </Text>
                  </View>
                  <Text style={styles.reportTopCampaign}>
                    Top: {report.topCampaign}
                  </Text>
                </View>
              </TouchableOpacity>
            ))}
          </View>
        </View>

        {/* Quick Actions */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Quick Actions</Text>
          <View style={styles.actionButtons}>
            <TouchableOpacity style={styles.actionButton}>
              <Download size={20} color={theme.colors.primary} />
              <Text style={styles.actionButtonText}>Download PDF</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.actionButton}>
              <Calendar size={20} color={theme.colors.primary} />
              <Text style={styles.actionButtonText}>Custom Range</Text>
            </TouchableOpacity>
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceLight,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.colors.text,
  },
  shareButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  periodContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 12,
  },
  periodButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
  },
  periodButtonActive: {
    backgroundColor: theme.colors.primary,
  },
  periodText: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.textSecondary,
  },
  periodTextActive: {
    color: theme.colors.background,
  },
  summaryCard: {
    marginHorizontal: 20,
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  summaryIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0, 217, 163, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  summaryContent: {
    flex: 1,
  },
  summaryLabel: {
    fontSize: 13,
    color: theme.colors.textSecondary,
    marginBottom: 6,
  },
  summaryValue: {
    fontSize: 32,
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: 8,
  },
  growthBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  growthText: {
    fontSize: 13,
    color: theme.colors.success,
    fontWeight: '500',
  },
  summaryDivider: {
    height: 1,
    backgroundColor: theme.colors.surfaceLight,
    marginVertical: 16,
  },
  summaryStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  summaryStat: {
    alignItems: 'center',
  },
  summaryStatLabel: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginBottom: 6,
  },
  summaryStatValue: {
    fontSize: 20,
    fontWeight: '600',
    color: theme.colors.text,
  },
  summaryStatDivider: {
    width: 1,
    backgroundColor: theme.colors.surfaceLight,
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: 16,
  },
  downloadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(0, 217, 163, 0.1)',
    borderRadius: 8,
  },
  downloadText: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.colors.primary,
  },
  paymentCards: {
    gap: 12,
  },
  paymentCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 16,
  },
  paymentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  paymentIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 217, 163, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  paymentMethod: {
    fontSize: 15,
    fontWeight: '500',
    color: theme.colors.text,
  },
  paymentAmount: {
    fontSize: 24,
    fontWeight: '600',
    color: theme.colors.text,
    marginBottom: 12,
  },
  progressBar: {
    height: 6,
    backgroundColor: theme.colors.surfaceLight,
    borderRadius: 3,
    marginBottom: 8,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: theme.colors.primary,
    borderRadius: 3,
  },
  paymentPercentage: {
    fontSize: 12,
    color: theme.colors.textSecondary,
  },
  reportsList: {
    gap: 12,
  },
  reportCard: {
    flexDirection: 'row',
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 16,
  },
  reportIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 217, 163, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  reportContent: {
    flex: 1,
  },
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  reportPeriod: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.colors.text,
  },
  reportGrowth: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    gap: 4,
  },
  reportGrowthText: {
    fontSize: 12,
    fontWeight: '600',
  },
  reportStats: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  reportStat: {
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  reportStatSeparator: {
    fontSize: 13,
    color: theme.colors.textTertiary,
    marginHorizontal: 8,
  },
  reportTopCampaign: {
    fontSize: 12,
    color: theme.colors.textTertiary,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    paddingVertical: 16,
    gap: 8,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.text,
  },
});
